### ISSUE TITLE
Confirmation

### ISSUE THREAD

**Issue by enirtak** [TimyVillarmia/CSharp-Data-Structures-Algorithms#1]
Selection Sort at line 35, should the max equal to i?

**Comment by TimyVillarmia** [comment]
Thank you for raising the concern about the selection sort at line 35. However, it seems there might be a misunderstanding. In the selection sort algorithm, the variable "max" is not required to be equal to "i."  The purpose of max = 0 is to swap largest elements at the back of the array.  I believe you are referring to the function SelectionSortFront at line 73.

**Comment by enirtak** [comment]
Thanks for the clarification!
